Comandeer/rollup-lib-bundler

src/bundler.js, src/packageParser.js, tests/bundler.js, tests/packageParser.js
=> Change way of parsing author's info

package.json
Closes #13
Fixes #
Description of proposed changes:
-
=> fix(package): update rollup to version 0.45.0

CHANGELOG.md, package-lock.json, package.json, rollup.config.es2015.js, src/bundler.js
=> Switch to rollup-plugin-babel-minify

CHANGELOG.md, package-lock.json, package.json, rollup.config.es2015.js, rollup.config.es5.js, src/bundler.js, tests/bundler.js
=> fix(package): update rollup to version 0.49.2

.travis.yml
=> ci(Travis): enable Node 8

package-lock.json, package.json
=> Integration with commitplease

.gitignore, .travis.yml, README.md, package-lock.json, package.json
=> Add code coverage

src/bundler.js, src/generateBanner.js, src/index.js, tests/bundler.js, tests/generateBanner.js
=> Introduce generateBanner function

README.md, package-lock.json, package.json, rollup.config.es5.js, src/bundler.js, tests/fixtures/testPackage/src/index.js
=> Switch to latest preset

.babelrc, package-lock.json, package.json, rollup.config.es5.js, src/bundler.js, tests/bundler.js, tests/generateBanner.js, tests/packageParser.js, tests/rlb.js
=> Move to testing source

package-lock.json, package.json
=> Drop prepublish script

package-lock.json, package.json
=> Hide commitplease behind Husky

.travis.yml, package-lock.json
=> Greenkeeper lockfile integration

src/bundler.js, tests/bundler.js
=> feat(bundler): add new line after banner

CHANGELOG.md, package.json
=> Fix incorrect version of package in banner comment

package.json
=> chore(script): change mocha --compilers to --require option

CHANGELOG.md, package-lock.json, package.json
=> Add babel-core as dependency

package-lock.json, package.json, src/bundler.js, tests/bundler.js
=> Get rid of deprecated rollup option

.travis.yml, CHANGELOG.md, package.json
=> Remove support for Node<6

package-lock.json, package.json, src/bundler.js, tests/bundler.js
=> ESM version of bundle is not transpiled

CHANGELOG.md, src/bundler.js, src/packageParser.js, tests/bundler.js, tests/packageParser.js
=> Rename bundle modes

tests/bundler.js, tests/generateBanner.js, tests/packageParser.js, tests/rlb.js
=> refactor(tests): rewrite to ESM syntax

tests/bundler.js
Added test is complex one, which checks whole integration of rollup plugins with bundler flow: order
of execution and config.
closes #78
-
=> test(bundler): add test for plugins

.travis.yml, CHANGELOG.md
=> Update to node 10

.travis.yml, package-lock.json, package.json
Fixes #88.
Closes #85.
Closes #86.
Closes #87.
=> Force npm install on Travis CI

CHANGELOG.md, package-lock.json, package.json, tests/bundler.js
=> Fix incorrect sourcemaps for bundles

.babelrc, .gitattributes, .travis.yml, CHANGELOG.md, package-lock.json, package.json, tests/cli.js, tests/helpers/createFixtureTest.js, tests/rlb.js
Closes #128.
Closes #129.
Closes #84.
=> Update Node and OS support

src/packageParser.js
Fixes #166 
Description of proposed changes:
- Convert to string before parsing.
This PR will close #166
=> Convert buffer to string before parsing

package-lock.json, package.json, src/bundler.js, tests/bundler.js, tests/fixtures/jsonPackage/package.json, tests/fixtures/jsonPackage/src/index.js
Fixes #155
Description of proposed changes:
- Use `@rollup/plugin-json` to support JSON files
=> Support JSON files

.github/workflows/ci.yml, CHANGELOG.md, package.json, src/targets.js, tests/targets.js
=> Drop support for Node 10

.github/workflows/ci.yml, CHANGELOG.md
=> Add official support for Node 16

CHANGELOG.md, package-lock.json, package.json
=> chore(package): update dependencies

CHANGELOG.md, package-lock.json, package.json, src/OutputController.js, src/bundler.js, tests/OutputController.js, tests/helpers/createDummyStream.js, tests/packageParser.js
=> Add better output

.gitignore, CHANGELOG.md, src/OutputController.js, src/bundler.js, src/index.js, src/rlb.js, tests/OutputController.js, tests/bundler.js, tests/cli.js, tests/fixtures/errorPackage/package.json, tests/fixtures/errorPackage/src/index.js, tests/fixtures/externalDepPackage/package.json, tests/fixtures/externalDepPackage/src/index.js, tests/helpers/createFixtureTest.js, tests/helpers/createFlowTest.js, tests/index.js
=> Unzalgoing code + error handling

package-lock.json, package.json, src/OutputController.js, src/rlb.js, tests/OutputController.js
=> Replace `gauge` with `@comandeer/cli-spinner`

package.json
=> chore(package): remove clutter

CHANGELOG.md, README.md, src/rlb.js, tests/cli.js
=> Clean `dist/` before bundling

CHANGELOG.md, src/OutputController.js, tests/OutputController.js, tests/__helpers__/createDummyStream.js
=> Log warnings into `stderr`

CHANGELOG.md, package-lock.json, package.json
=> chore(package): mark `rimraf` as production dependency

.github/workflows/ci.yml, CHANGELOG.md, package-lock.json, package.json
=> Add support for Node 18 and drop support for Node 12 & 14

CHANGELOG.md, README.md, src/bundler.js, src/packageParser.js, tests/__fixtures__/noCJSPackage/package.json, tests/__fixtures__/noCJSPackage/src/index.js, tests/__fixtures__/noCJSSubPathExportsPackage/package.json, tests/__fixtures__/noCJSSubPathExportsPackage/src/chunk.js, tests/__fixtures__/noCJSSubPathExportsPackage/src/index.js, tests/__fixtures__/packageParser/noCJSExports.json, tests/__fixtures__/packageParser/noCJSSubPathExports.json, tests/bundler.js, tests/cli.js, tests/packageParser.js
=> Make CJS builds optional

.github/workflows/ci.yml
=> ci(gha): update used actions

CHANGELOG.md, src/packageParser.js, tests/__helpers__/bundleChecks.js, tests/__helpers__/createFixtureTest.js, tests/bundler.js, tests/cli.js
=> refactor(*): replace sync IO operations with async ones

CHANGELOG.md, package-lock.json, package.json, src/bundler.js, src/packageParser.js, src/rlb.js, tests/__helpers__/bundleChecks.js, tests/__helpers__/createFixtureTest.js, tests/bundler.js, tests/cli.js, tests/packageParser.js
Closes #229.
Closes #237.
Closes #240.
=> Fix for incorrect type bundling and test revamp

CHANGELOG.md, package-lock.json, package.json, src/bundler.js, tests/__fixtures__/tsComplexPackage/package.json, tests/__fixtures__/tsComplexPackage/src/fn.ts, tests/__fixtures__/tsComplexPackage/src/index.ts, tests/__fixtures__/tsComplexPackage/src/subdir/add.ts, tests/__fixtures__/tsComplexPackage/src/subdir/submodule.ts, tests/__fixtures__/tsComplexPackage/tsconfig.json, tests/__helpers__/bundleChecks.js, tests/bundler.js, tests/cli.js
=> Fix for incorrect type definitions bundling in projects with subdirectories

CHANGELOG.md, README.md, src/packageParser.js, tests/__fixtures__/dynamicExternalImport/package.json, tests/__fixtures__/errorPackage/package.json, tests/__fixtures__/externalDepPackage/package.json, tests/__fixtures__/jsonPackage/package.json, tests/__fixtures__/testPackage/package.json, tests/packageParser.js
=> Remove support for non-`exports` entrypoints

CHANGELOG.md, bin/bundler, bin/bundler.mjs, package-lock.json, package.json, tests/cli.js
=> Replace non-exports entrypoints with exports ones

CHANGELOG.md, package-lock.json, package.json, src/bundler.js
=> Rewrite type bundler to use virtual FS instead of a temporary directory

CHANGELOG.md, src/bundler.js, src/bundler/bundleTypes.js
=> Load config from tsconfig.json file

CHANGELOG.md, src/bundler.js, tests/__fixtures__/babelTranspilationTSPackage/package.json, tests/__fixtures__/babelTranspilationTSPackage/src/chunk.js, tests/__fixtures__/babelTranspilationTSPackage/src/index.ts, tests/__fixtures__/babelTranspilationTSPackage/tsconfig.json, tests/__helpers__/checkDistFiles.js, tests/__helpers__/macros/testCLI.js, tests/cli.js
=> Transpile TS source files

.eslintignore, package.json
=> chore(package): add lint npm script and activate it for pretest

CHANGELOG.md, package-lock.json, package.json, src/bundler.js, tests/__fixtures__/jsonESMPackage/package.json, tests/__fixtures__/jsonESMPackage/src/index.js, tests/cli.js
=> Add support for import assertions

src/bundler/bundleTypes.js, src/packageParser.js, tests/__helpers__/checkDistFiles.js, tests/__helpers__/createTemporaryFixtureDirectory.js, tests/__helpers__/macros/testCLI.js, tests/__helpers__/removeArtifacts.js
=> refactor(*): replace dynamic imports with static ones

CHANGELOG.md, src/bundler.js, tests/cli.js
=> feat(bundler): remove warning for skippin CJS build

.github/workflows/ci.yml, CHANGELOG.md
=> Add official support for Node 20

CHANGELOG.md, src/bundler.js, src/bundler/fixBinPermissions.js, src/packageParser.js, tests/cli.js, tests/packageParser.js
=> Fix for incorrect file permissions for bundled executables

CHANGELOG.md, package-lock.json, package.json, src/bundler/bundleTypes.js, tests/__fixtures__/mtsAndCTSPackage/package.json, tests/__fixtures__/mtsAndCTSPackage/src/chunk.cts, tests/__fixtures__/mtsAndCTSPackage/src/index.mts, tests/__fixtures__/mtsAndCTSPackage/tsconfig.json, tests/cli.js
=> Add support for bundling `.d.cts` and `.d.mts` files

tests/__helpers__/macros/testCLI.js
=> test(cli): fix incorrect async assertion

package.json, tests/__helpers__/macros/testCLI.js
=> Switch CLI testing to source

src/OutputController.js, tests/OutputController.js, tests/__helpers__/createDummyConsole.js, tests/__helpers__/createDummySpinner.js
=> Refactor `OutputController`

tests/__fixtures__/nonStandardMultipleDistJSPackage/package.json, tests/cli.js
=> test(cli): update fixture for multiple non-standard dist directories

.github/workflows/ci.yml, CHANGELOG.md, package-lock.json, package.json, tests/__helpers__/createDummyStream.ts
Closes #303.
Closes #305.
Closes #306.
=> Fix incorrect published packages

.github/workflows/prLinter.yml
=> ci(prlinter): add PR title linting GHA

.github/workflows/ci.yml, .github/workflows/prLinter.yml, CHANGELOG.md, package.json, tests/cli.ts
=> feat: update support for Node.js

.github/workflows/ci.yml
=> ci(gha): update action versions

.github/workflows/ci.yml
=> ci(gha): update CodeCov action config

package.json, tests/__fixtures__/bin/pathWithoutDot/package.json, tests/__fixtures__/bin/pathWithoutDot/src/__bin__/test-package.js, tests/__fixtures__/bin/pathWithoutDot/src/index.js, tests/cli.ts
=> refactor(package): update CLI path

CHANGELOG.md, src/OutputController.ts, src/index.ts, tests/OutputController.ts
=> fix(outputcontroller): hide spinner before displaying any results

CHANGELOG.md, src/bundler.ts, tests/__fixtures__/bin/complexBinTSPackage/tsconfig.json, tests/__fixtures__/bin/simpleBinTSPackage/tsconfig.json, tests/__fixtures__/bundles/importingOtherBundlesTSPackage/tsconfig.json, tests/__fixtures__/distDirs/nonStandardDistComplexBinTSPackage/tsconfig.json, tests/__fixtures__/distDirs/nonStandardDistSimpleBinTSPackage/tsconfig.json, tests/__fixtures__/distDirs/nonStandardDistTSPackage/tsconfig.json, tests/__fixtures__/targets/customNodeTargetTS/tsconfig.json, tests/__fixtures__/types/bundleWithoutDTSFilePackage/tsconfig.json, tests/__fixtures__/types/bundlesInNonStandardDistDirsPackage/tsconfig.json, tests/__fixtures__/typescript/babelTranspilationTSPackage/tsconfig.json, tests/__fixtures__/typescript/customOutDir/tsconfig.json, tests/__fixtures__/typescript/hardcodedCompilerOptions/package.json, tests/__fixtures__/typescript/hardcodedCompilerOptions/src/fn.ts, tests/__fixtures__/typescript/hardcodedCompilerOptions/src/index.ts, tests/__fixtures__/typescript/hardcodedCompilerOptions/tsconfig.json, tests/__fixtures__/typescript/hardcodedModuleResolutionCompilerOption/package.json, tests/__fixtures__/typescript/hardcodedModuleResolutionCompilerOption/src/fn.ts, tests/__fixtures__/typescript/hardcodedModuleResolutionCompilerOption/src/index.ts, tests/__fixtures__/typescript/hardcodedModuleResolutionCompilerOption/tsconfig.json, tests/__fixtures__/typescript/mtsAndCTSPackage/tsconfig.json, tests/__fixtures__/typescript/tsComplexPackage/tsconfig.json, tests/__fixtures__/typescript/tsPackage/tsconfig.json, tests/cli.ts
=> feat(bundler): hardcode TS compiler options
